let jsonObject = {
  latest_transactions: [
    {
      account_id: "gW7ReMwwlvIEog1kQpy1Fobz51RrmbIE54aVa",
      account_owner: null,
      amount: 5.4,
      authorized_date: "2025-01-18",
      authorized_datetime: null,
      category: ["Travel", "Taxi"],
      category_id: "22016000",
      check_number: null,
      counterparties: [
        {
          confidence_level: "VERY_HIGH",
          entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
          logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
          name: "Uber",
          phone_number: null,
          type: "merchant",
          website: "uber.com",
        },
      ],
      date: "2025-01-19",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
      merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
      merchant_name: "Uber",
      name: "Uber 063015 SF**POOL**",
      payment_channel: "online",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "VERY_HIGH",
        detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
        primary: "TRANSPORTATION",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
      transaction_code: null,
      transaction_id: "45ZEQnwwyMc5vqJQbMdJCR3jWvrpVRiJV3v41",
      transaction_type: "special",
      unofficial_currency_code: null,
      website: "uber.com",
    },
    {
      account_id: "8EZnLJ44yWFwDaQebmLQuJepzEw1veiW8K41P",
      account_owner: null,
      amount: 25,
      authorized_date: "2025-01-18",
      authorized_datetime: null,
      category: ["Payment", "Credit Card"],
      category_id: "16001000",
      check_number: null,
      counterparties: [],
      date: "2025-01-19",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: null,
      merchant_entity_id: null,
      merchant_name: null,
      name: "CREDIT CARD 3333 PAYMENT *//",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "LOW",
        detailed: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
        primary: "LOAN_PAYMENTS",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png",
      transaction_code: null,
      transaction_id: "eWw9jM44ebIGEKbq81lbi3aQq5nJV3UrBVbeD",
      transaction_type: "special",
      unofficial_currency_code: null,
      website: null,
    },
    {
      account_id: "WDk1EXwwqKSkp3eEyr8euAdl8yNo1dH6jwA9e",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Shops", "Sporting Goods"],
      category_id: "19046000",
      check_number: null,
      counterparties: [],
      date: "2025-01-28",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: null,
      merchant_entity_id: null,
      merchant_name: null,
      name: "Madison Bicycle Shop",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "LOW",
        detailed: "GENERAL_MERCHANDISE_SPORTING_GOODS",
        primary: "GENERAL_MERCHANDISE",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
      transaction_code: null,
      transaction_id: "LDPd7pGGxgSb7vRq8PXRS8MvgKzLl8FkK9xdg",
      transaction_type: "place",
      unofficial_currency_code: null,
      website: null,
    },
    {
      account_id: "WDk1EXwwqKSkp3eEyr8euAdl8yNo1dH6jwA9e",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants", "Fast Food"],
      category_id: "13005032",
      check_number: null,
      counterparties: [
        {
          confidence_level: "VERY_HIGH",
          entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
          logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
          name: "KFC",
          phone_number: null,
          type: "merchant",
          website: "kfc.com",
        },
      ],
      date: "2025-01-28",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
      merchant_entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
      merchant_name: "KFC",
      name: "KFC",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "VERY_HIGH",
        detailed: "FOOD_AND_DRINK_FAST_FOOD",
        primary: "FOOD_AND_DRINK",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
      transaction_code: null,
      transaction_id: "pnAr8MbbkaIE5N9dZQg9FZz7LVN4gZipjKv8D",
      transaction_type: "place",
      unofficial_currency_code: null,
      website: "kfc.com",
    },
    {
      account_id: "WDk1EXwwqKSkp3eEyr8euAdl8yNo1dH6jwA9e",
      account_owner: null,
      amount: 2078.5,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Payment"],
      category_id: "16000000",
      check_number: null,
      counterparties: [],
      date: "2025-01-28",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: null,
      merchant_entity_id: null,
      merchant_name: null,
      name: "AUTOMATIC PAYMENT - THANK",
      payment_channel: "online",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "LOW",
        detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
        primary: "GENERAL_MERCHANDISE",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
      transaction_code: null,
      transaction_id: "onyKg1ZZdxIGNMJwnV9JidrDZ6nlgdto5KZGR",
      transaction_type: "special",
      unofficial_currency_code: null,
      website: null,
    },
    {
      account_id: "WDk1EXwwqKSkp3eEyr8euAdl8yNo1dH6jwA9e",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      check_number: null,
      counterparties: [],
      date: "2025-01-29",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: null,
      merchant_entity_id: null,
      merchant_name: null,
      name: "Tectra Inc",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "LOW",
        detailed: "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
        primary: "ENTERTAINMENT",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png",
      transaction_code: null,
      transaction_id: "1EWoj6rr7PF7xnP84B6PFjGKgW7NRjupXmkEy",
      transaction_type: "place",
      unofficial_currency_code: null,
      website: null,
    },
    {
      account_id: "gW7ReMwwlvIEog1kQpy1Fobz51RrmbIE54aVa",
      account_owner: null,
      amount: 6.33,
      authorized_date: "2025-01-31",
      authorized_datetime: null,
      category: ["Travel", "Taxi"],
      category_id: "22016000",
      check_number: null,
      counterparties: [
        {
          confidence_level: "VERY_HIGH",
          entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
          logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
          name: "Uber",
          phone_number: null,
          type: "merchant",
          website: "uber.com",
        },
      ],
      date: "2025-02-01",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
      merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
      merchant_name: "Uber",
      name: "Uber 072515 SF**POOL**",
      payment_channel: "online",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "VERY_HIGH",
        detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
        primary: "TRANSPORTATION",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
      transaction_code: null,
      transaction_id: "ab7na6JJNoIKGjaJwypac5ELJDGKR5sZJeEV9",
      transaction_type: "special",
      unofficial_currency_code: null,
      website: "uber.com",
    },
    {
      account_id: "WDk1EXwwqKSkp3eEyr8euAdl8yNo1dH6jwA9e",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Travel", "Airlines and Aviation Services"],
      category_id: "22001000",
      check_number: null,
      counterparties: [
        {
          confidence_level: "VERY_HIGH",
          entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
          logo_url:
            "https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
          name: "United Airlines",
          phone_number: null,
          type: "merchant",
          website: "united.com",
        },
      ],
      date: "2025-02-03",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      logo_url:
        "https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
      merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
      merchant_name: "United Airlines",
      name: "United Airlines",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: {
        confidence_level: "VERY_HIGH",
        detailed: "TRAVEL_FLIGHTS",
        primary: "TRAVEL",
      },
      personal_finance_category_icon_url:
        "https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
      transaction_code: null,
      transaction_id: "MDPaeg99dES98xjBbPzjCxRn8pZ7QxiLp7WG5",
      transaction_type: "special",
      unofficial_currency_code: null,
      website: "united.com",
    },
  ],
};

const broadCategories = {
  Transportation: ["Travel", "Taxi", "Airlines and Aviation Services"],
  Food: ["Food and Drink", "Restaurants", "Fast Food"],
  Payments: ["Payment", "Credit Card"],
  "Loan Payments": ["Loan Payments", "Credit Card Payments"],
  Other: ["Shops", "Sporting Goods"],
};

const aggregatedAmounts = {};

// Aggregation logic
jsonObject.latest_transactions.forEach((transaction) => {
  const { category, amount } = transaction;
  category.forEach((cat) => {
    const broadCategory = Object.keys(broadCategories).find((key) =>
      broadCategories[key].includes(cat)
    );
    if (broadCategory) {
      if (!aggregatedAmounts[broadCategory]) {
        aggregatedAmounts[broadCategory] = 0;
      }
      aggregatedAmounts[broadCategory] += amount;
    }
  });
});

// Exporting aggregatedAmounts
module.exports = aggregatedAmounts;
